/* Auth */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CHECK_SESSION_SUCCESS = 'CHECK_SESSION_SUCCESS';

/* Loader */
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILED = 'GET_ME_FAILED';

export const SAVE_ONLINE_USER = 'SAVE_ONLINE_USER';

/* Driver */
export const DRIVERS_GET_SUCCESS = 'DRIVERS_GET_SUCCESS';
export const DRIVERS_FILTER_GET_SUCCESS = 'DRIVERS_FILTER_GET_SUCCESS';
export const DRIVERS_EMPTY_SUCCESS = 'DRIVERS_EMPTY_SUCCESS';
export const DRIVERS_DELETE_SUCCESS = 'DRIVERS_DELETE_SUCCESS';
export const DRIVERS_GET_DETAILS_SUCCESS = 'DRIVERS_GET_DETAILS_SUCCESS';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const REPORT_DRIVERS_GET_SUCCESS = 'REPORT_DRIVERS_GET_SUCCESS';

/* Bus */
export const BUS_GET_SUCCESS = 'BUS_GET_SUCCESS';
export const BUS_FILTER_GET_SUCCESS = 'BUS_FILTER_GET_SUCCESS';
export const BUS_EMPTY_SUCCESS = 'BUS_EMPTY_SUCCESS';
export const BUS_DELETE_SUCCESS = 'BUS_DELETE_SUCCESS';
export const BUS_GET_DETAILS_SUCCESS = 'BUS_GET_DETAILS_SUCCESS';


/* Shift */
export const SHIFT_GET_SUCCESS = 'SHIFT_GET_SUCCESS';
export const SHIFT_FILTER_GET_SUCCESS = 'SHIFT_FILTER_GET_SUCCESS';
export const SHIFT_EMPTY_SUCCESS = 'SHIFT_EMPTY_SUCCESS';
export const SHIFT_DELETE_SUCCESS = 'SHIFT_DELETE_SUCCESS';
export const SHIFT_GET_DETAILS_SUCCESS = 'SHIFT_GET_DETAILS_SUCCESS';


// Emails
export const GET_EMAILS = 'GET_EMAILS';
export const ADD_EMAIL = 'ADD_EMAIL';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';

export const ROLES_GET_SUCCESS = 'ROLES_GET_SUCCESS';
export const ROLES_EMPTY = 'ROLES_EMPTY';
export const SUB_ADMIN_GET_SUCCESS = 'SUB_ADMIN_GET_SUCCESS';
export const SUB_ADMIN_EMPTY = 'SUB_ADMIN_EMPTY';
export const BOOKING_MANAGER_GET_SUCCESS = 'BOOKING_MANAGER_GET_SUCCESS';

export const UNIVERSITIES_GET_SUCCESS = 'UNIVERSITIES_GET_SUCCESS';
export const EMPTY_UNIVERSITIES_SUCCESS = 'EMPTY_UNIVERSITIES_SUCCESS';
export const COUNTRIES_GET_SUCCESS = 'COUNTRIES_GET_SUCCESS';
export const CITIES_GET_SUCCESS = 'CITIES_GET_SUCCESS';
export const LANGUAGES_GET_SUCCESS = 'LANGUAGES_GET_SUCCESS';
export const STRENGTH_CATEGORIES_GET_SUCCESS = 'STRENGTH_CATEGORIES_GET_SUCCESS';
export const EMPTY_STRENGTHS_SUCCESS = 'EMPTY_STRENGTHS_SUCCESS';
export const STRENGTHS_GET_SUCCESS = 'STRENGTHS_GET_SUCCESS';
export const NOTIFICATION_GET_SUCCESS = 'NOTIFICATION_GET_SUCCESS';
export const EMAIL_SETTING_GET_SUCCESS = 'EMAIL_SETTING_GET_SUCCESS';
export const APP_SETTING_GET_SUCCESS = 'APP_SETTING_GET_SUCCESS';
export const APP_SETTING_CHANGE_SUCCESS = 'APP_SETTING_CHANGE_SUCCESS';
export const APP_SETTING_UPDATE_SUCCESS = 'APP_SETTING_UPDATE_SUCCESS';

export const PEER_GROUP_GET_SUCCESS = 'PEER_GROUP_GET_SUCCESS';
export const PEER_GROUP_DETAILS_GET_SUCCESS = 'PEER_GROUP_DETAILS_GET_SUCCESS';
export const PEER_GROUP_INVOICE_DETAILS_GET_SUCCESS = 'PEER_GROUP_INVOICE_DETAILS_GET_SUCCESS';
export const PEER_FILTER_GET_SUCCESS = 'PEER_FILTER_GET_SUCCESS';
export const PEER_EMPTY_GET_SUCCESS = 'PEER_EMPTY_GET_SUCCESS';

export const DASHBOARD_STATS_GET_SUCCESS = 'DASHBOARD_STATS_GET_SUCCESS';

export const INVOICES_GET_SUCCESS = 'INVOICES_GET_SUCCESS';
export const INVOICES_EMPTY = 'INVOICES_EMPTY';

export const INVOICE_PLANS_GET_SUCCESS = 'INVOICE_PLANS_GET_SUCCESS';
export const INVOICE_PLANS_EMPTY = 'INVOICE_PLANS_EMPTY';